# Generated by Django 3.0.6 on 2020-06-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.IntegerField()),
                ('sale_started', models.DateTimeField(default=None)),
                ('group', models.ManyToManyField(to='groups.Group')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.Sale')),
            ],
        ),
    ]
