# Generated by Django 3.0.6 on 2020-06-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='sale_started',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
