# Generated by Django 3.0.6 on 2020-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_auto_20200609_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='sale_started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
