# Generated by Django 3.0.6 on 2020-06-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0001_initial'),
        ('system_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='accesses.Access'),
        ),
    ]
